// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShrimplyAPI.Data;

#nullable disable

namespace ShrimplyAPI.Migrations
{
    [DbContext(typeof(ShrimplyApiDbContext))]
    [Migration("20230722221629_SeedShrimpsTable")]
    partial class SeedShrimpsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShrimplyAPI.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b05"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b06"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b07"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("ShrimplyAPI.Models.Domain.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b02"),
                            Code = "CAR",
                            ImageUrl = "image1",
                            Name = "Caridina"
                        },
                        new
                        {
                            Id = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b03"),
                            Code = "NEO",
                            ImageUrl = "image2",
                            Name = "Neocaridina"
                        },
                        new
                        {
                            Id = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b04"),
                            Code = "SUL",
                            ImageUrl = "image3",
                            Name = "Sulawesi"
                        });
                });

            modelBuilder.Entity("ShrimplyAPI.Models.Domain.Shrimp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Shrimps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0505de0-424c-4388-af4b-b1fbd629433a"),
                            Description = "Pure White Line Shrimp",
                            DifficultyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b06"),
                            FamilyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b02"),
                            ImageUrl = "image4",
                            Name = "Pure White Line"
                        },
                        new
                        {
                            Id = new Guid("3463cedb-0c49-469c-8a5d-dfbc9105b464"),
                            Description = "Pure Red Line Shrimp",
                            DifficultyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b06"),
                            FamilyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b02"),
                            ImageUrl = "image5",
                            Name = "Pure Red Line"
                        },
                        new
                        {
                            Id = new Guid("bceef984-27f2-4bec-b02d-25ef3d5acd18"),
                            Description = "Pure Black Line Shrimp",
                            DifficultyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b06"),
                            FamilyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b02"),
                            ImageUrl = "image6",
                            Name = "Pure Black Line"
                        },
                        new
                        {
                            Id = new Guid("dd24d83a-c285-45e8-a26b-969ef8fe2970"),
                            Description = "Yellow Shrimp",
                            DifficultyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b05"),
                            FamilyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b03"),
                            ImageUrl = "image7",
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("0ddf58d2-0dda-4ea6-9a49-86695ad9d569"),
                            Description = "White Pearl",
                            DifficultyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b05"),
                            FamilyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b03"),
                            ImageUrl = "image8",
                            Name = "White Pearl"
                        },
                        new
                        {
                            Id = new Guid("48712e81-383b-41d6-8879-3b0b1ace78d8"),
                            Description = "Cardinal",
                            DifficultyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b07"),
                            FamilyId = new Guid("58ba0c1c-d7ef-4b22-80a9-8adf8c442b04"),
                            ImageUrl = "image9",
                            Name = "Cardinal"
                        });
                });

            modelBuilder.Entity("ShrimplyAPI.Models.Domain.Shrimp", b =>
                {
                    b.HasOne("ShrimplyAPI.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShrimplyAPI.Models.Domain.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Family");
                });
#pragma warning restore 612, 618
        }
    }
}
