// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShrimplyAPI.Data;

#nullable disable

namespace ShrimplyAPI.Migrations
{
    [DbContext(typeof(ShrimplyApiDbContext))]
    [Migration("20230721083929_seed Families and Difficulties")]
    partial class seedFamiliesandDifficulties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShrimplyAPI.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15e50b91-c664-49cd-a28d-67d579c05b2d"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("96e665e2-a9a8-4b41-91ed-e58d88b27563"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("1fa72dc6-283a-4010-ba17-0c78f1e3a6d6"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("ShrimplyAPI.Models.Domain.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c49eb27d-278e-4540-a5af-de134699267f"),
                            Code = "CAR",
                            ImageUrl = "image1",
                            Name = "Caridina"
                        },
                        new
                        {
                            Id = new Guid("f22c0219-c568-438e-8921-d3dc5761a6e3"),
                            Code = "NEO",
                            ImageUrl = "image2",
                            Name = "Neocaridina"
                        },
                        new
                        {
                            Id = new Guid("d9c63042-8115-4124-93ec-d5149e7d48a0"),
                            Code = "SUL",
                            ImageUrl = "image3",
                            Name = "Sulawesi"
                        });
                });

            modelBuilder.Entity("ShrimplyAPI.Models.Domain.Shrimp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Shrimps");
                });

            modelBuilder.Entity("ShrimplyAPI.Models.Domain.Shrimp", b =>
                {
                    b.HasOne("ShrimplyAPI.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShrimplyAPI.Models.Domain.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Family");
                });
#pragma warning restore 612, 618
        }
    }
}
